version: '2'

services:
  db:
    image: wodby/mariadb-alpine:1.3.3
    container_name: db
    environment:
        TZ: Europe/Copenhagen
    volumes:
      - ../mysql-data:/var/lib/mysql

  gemet:
    build: .
    container_name: gemet
    ports:
      - '8888:8888'
    depends_on:
      - db